# version for 'time'
sudo: true
language: perl6
perl6:
    - 2017.06

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y time

install:
    - rakudobrew build-zef
    # the following command avoids double-testing of the target module:
    - git clone https://github.com/tbrowder/Proc-More-Perl6.git
    - zef install ./Proc-More-Perl6
    - zef install --depsonly .
